Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
group = []
src     = Glob('*.c')
CPPPATH = [cwd, ]

CFLAGS = ' -c -ffunction-sections'

group = group + DefineGroup('Applications', src, depend = ['ZX_METER_DEMO'], CPPPATH = CPPPATH, CFLAGS=CFLAGS)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
