Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []

if GetDepend('AIC_I2C_DRV_TEST') and GetDepend('RT_USING_FINSH'):
    src = Glob('test_i2c_slave.c')

group = DefineGroup('test-i2c', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
