# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c')

CPPPATH = [cwd]
ASFLAGS = ''

group = DefineGroup('BLCMD', src, depend = ['BAREMETAL_HELLOWORLD'], CPPPATH = CPPPATH, ASFLAGS = ASFLAGS)

Return('group')
