// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_wft_ui1
void ui_wft_ui1_screen_init(void);
lv_obj_t * ui_wft_ui1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_ui1_Image_bg1;
lv_obj_t * ui_ui1_Image_bg2;
lv_obj_t * ui_ui1_Label_bgnum;
lv_obj_t * ui_ui1_Label_kmh;
lv_obj_t * ui_ui1_Slider_bat_left;
lv_obj_t * ui_ui1_Slider_bat_right;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Image22;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Image25;
lv_obj_t * ui_Image26;
lv_obj_t * ui_Image27;
lv_obj_t * ui_Image28;
lv_obj_t * ui_Image45;
lv_obj_t * ui_Image46;
lv_obj_t * ui_Image47;
lv_obj_t * ui_Image48;
lv_obj_t * ui_Label13;
// SCREEN: ui_wft_ui2
void ui_wft_ui2_screen_init(void);
lv_obj_t * ui_wft_ui2;
lv_obj_t * ui_ui2_Image_bg1;
lv_obj_t * ui_ui2_Image_bg2;
lv_obj_t * ui_ui2_Label_bgnum;
lv_obj_t * ui_ui2_Label_kmh;
lv_obj_t * ui_Image50;
lv_obj_t * ui_Image29;
lv_obj_t * ui_Image30;
lv_obj_t * ui_Image31;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Image32;
lv_obj_t * ui_Image33;
lv_obj_t * ui_Image34;
lv_obj_t * ui_Image35;
lv_obj_t * ui_Image36;
lv_obj_t * ui_Image38;
lv_obj_t * ui_Image39;
lv_obj_t * ui_Image37;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Image40;
lv_obj_t * ui_Image41;
lv_obj_t * ui_Image42;
lv_obj_t * ui_Image43;
lv_obj_t * ui_Image44;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label10;

lv_obj_t * ui_Image23;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Image49;
lv_obj_t * ui_Image51;
lv_obj_t * ui_Image52;
lv_obj_t * ui_Image53;
lv_obj_t * ui_Image54;
lv_obj_t * ui_Image55;
lv_obj_t * ui_Image56;
lv_obj_t * ui_Image57;
lv_obj_t * ui_Image58;
lv_obj_t * ui_Image59;
lv_obj_t * ui_Image60;

lv_obj_t * ui_Label12;
// lv_style_t type_40_fort;
// lv_style_t type_130_fort;





///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif


void user_font_init(void)
{
    static lv_ft_info_t infodd;
    // //字体 40
    // /*FreeType uses C standard file system, so no driver letter is required.*/
    // infodd.name = "/rodata/heitijian.ttf";
    // infodd.weight = 32;
    // infodd.style = FT_FONT_STYLE_NORMAL;
    // infodd.mem = NULL;
    // if(!lv_ft_font_init(&infodd)) 
    // {
    //   LV_LOG_ERROR("create failed.");
    //   printf("qwerwqfdsfasdfn\n");
    // } 

    // /*Create style with the new font*/
    // lv_style_init(&type_40_fort);
    // lv_style_set_text_font(&type_40_fort, infodd.font);
    // lv_style_set_text_align(&type_40_fort, LV_TEXT_ALIGN_CENTER);
    lv_style_set_text_color(&app_interface.font->style,lv_color_make(0xff,0xff,0xff));


    #if 0
    //字体 30
    /*FreeType uses C standard file system, so no driver letter is required.*/
    infodd.name = "/rodata/font1.ttf";
    infodd.weight = 30;
    infodd.style = FT_FONT_STYLE_NORMAL;
    infodd.mem = NULL;
    if(!lv_ft_font_init(&infodd)) 
    {
      LV_LOG_ERROR("create failed.");
      printf("qwerwqfdsfasdfn\n");
    } 

    /*Create style with the new font*/
    lv_style_init(&type_30_fort);
    lv_style_set_text_font(&type_30_fort, infodd.font);
    lv_style_set_text_align(&type_30_fort, LV_TEXT_ALIGN_CENTER);
    lv_style_set_text_color(&type_30_fort,lv_color_make(0xff,0xff,0xff));
    #endif


    //字体 130
    /*FreeType uses C standard file system, so no driver letter is required.*/
    // infodd.name = "/rodata/font2.ttf";
    // infodd.weight = 130;
    // infodd.style = FT_FONT_STYLE_NORMAL;
    // infodd.mem = NULL;
    // if(!lv_ft_font_init(&infodd)) 
    // {
    //   LV_LOG_ERROR("create failed.");
    //   printf("qwerwqfdsfasdfn\n");
    // } 

    // /*Create style with the new font*/
    // lv_style_init(&type_130_fort);
    // lv_style_set_text_font(&type_130_fort, infodd.font);
    // lv_style_set_text_align(&type_130_fort, LV_TEXT_ALIGN_CENTER);
    // lv_style_set_text_color(&type_130_fort,lv_color_make(0xff,0xff,0xff));
}
///////////////////// ANIMATIONS ////////////////////




static void arc_mid_anim(lv_timer_t *tmr)
{
    char _path[64];
    char buff[50];
    //static int step_list[] = {30, 20, 100, 60, 100,0,83,97};
    static int step_list[] = {0, 100};
    static int t1 = 0, step = 0;
    static int disp_count = 0,disp_flag = 1,disp_flag2 = 0;

    static int dongenng_count = 0;

    // static int starst_count = 0;

    // if(starst_count<=50)
    // {
    //     starst_count++;
    //     return;
    // }

    (void)tmr;





    dongenng_count=(dongenng_count+3)%360;

    sprintf(buff,"%d",t1);

    // disp_count++;
    // if(disp_count>=100)
    // {
    //     disp_count=0;
    //     disp_flag=(disp_flag+1)%2;
    //     //disp_flag=0;
    //     if(disp_flag==1)
    //     {
    //         #if 1
    //         lv_img_cache_invalidate_src(NULL);
    //         if(ui_wft_ui2)
    //         {
    //             lv_obj_del(ui_wft_ui2);
    //             ui_wft_ui2=NULL;
    //         }
    //         if(ui_wft_ui1==NULL)
    //         {
                
    //             ui_wft_ui1_screen_init();
    //             lv_disp_load_scr(ui_wft_ui1);
    //         }
    //         //lv_obj_invalidate(lv_scr_act());//重绘屏幕
    //         #else
    //         lv_img_cache_invalidate_src(NULL);
    //         lv_disp_load_scr(ui_wft_ui1);
    //         #endif
    //     }
    //     else
    //     {
    //         #if 1
    //         lv_img_cache_invalidate_src(NULL);
    //         if(ui_wft_ui1)
    //         {
    //             lv_obj_del(ui_wft_ui1);
    //             ui_wft_ui1=NULL;
    //         }
    //         if(ui_wft_ui2==NULL)
    //         {
                
    //             ui_wft_ui2_screen_init();
    //             lv_disp_load_scr(ui_wft_ui2);
    //         }
    //         //lv_obj_invalidate(lv_scr_act());//重绘屏幕
    //         #else
    //         lv_img_cache_invalidate_src(NULL);
    //         lv_disp_load_scr(ui_wft_ui2);
    //         #endif
    //     }
    // }
       
    
    // #if 0
    if(t1 > step_list[step])
    {
        if((t1-step_list[step])>50)
        {
            t1 = t1 -3;
        }
        if((t1-step_list[step])>20)
        {
            t1 = t1 - 2;
        }
        else
        {
            t1 = t1 - 1;
        }
        
    }
    else if(t1 < step_list[step])
    {
        if((step_list[step]-t1)>50)
        {
            t1 = t1 + 3;
        }
        if((step_list[step]-t1)>20)
        {
            t1 = t1 + 2;
        }
        else
        {
            t1 = t1 + 1;
        }
    }
    else
    {
        step = (step < (sizeof(step_list) / sizeof(int) - 1)) ? (step + 1) : 0;
    }

    // #else
    // if(t1 > step_list[step])
    // {
    //     t1 = t1 - 1;
    // }
    // else if(t1 < step_list[step])
    // {
    //     t1 = t1 + 1;
    // }
    // else
    // {
    //     step = (step < (sizeof(step_list) / sizeof(int) - 1)) ? (step + 1) : 0;
    // }
    // #endif


    // if((disp_flag==1)&&(ui_wft_ui1))
    // {

    //     #if 1
        if(t1>=60)
        {
            if(disp_flag2!=1)
            {
                disp_flag2=1;

                lv_img_cache_invalidate_src(NULL);
                //lv_img_cache_set_size(5);
                lv_img_set_src(ui_ui1_Image_bg1, SRC2_PATH_HEAD"red_1.jpg");
                lv_img_set_src(ui_ui1_Image_bg2, SRC2_PATH_HEAD"red_2.png");
            }
        }
        else if(t1>=30)
        {
            if(disp_flag2!=2)
            {
                disp_flag2=2;

                lv_img_cache_invalidate_src(NULL);
                //lv_img_cache_set_size(5);
                lv_img_set_src(ui_ui1_Image_bg1, SRC2_PATH_HEAD"orange_1.jpg");
                lv_img_set_src(ui_ui1_Image_bg2, SRC2_PATH_HEAD"orange_2.png");
            }
        }
        else
        {
            if(disp_flag2!=3)
            {
                disp_flag2=3;

                lv_img_cache_invalidate_src(NULL);
                //lv_img_cache_set_size(5);
                lv_img_set_src(ui_ui1_Image_bg1, SRC2_PATH_HEAD"green_1.jpg");
                lv_img_set_src(ui_ui1_Image_bg2, SRC2_PATH_HEAD"green_2.png");
            }
        }
        // #endif
        
        lv_label_set_text(ui_ui1_Label_bgnum, buff);
        lv_img_set_angle(ui_ui1_Image_bg1, dongenng_count*10);
        lv_img_set_angle(ui_ui1_Image_bg2, 3600-dongenng_count*10);
        //lv_img_set_angle(ui_ui1_Image_bg3, 3600-dongenng_count*10);
        //lv_obj_invalidate(lv_scr_act());//重绘屏幕
        

    // }
    // else if((disp_flag==0)&&(ui_wft_ui2))
    // {
       
    //     if(t1>=60)
    //     {
    //         if(disp_flag2!=1)
    //         {
    //             disp_flag2=1;
    //             lv_img_cache_invalidate_src(NULL);
    //             lv_img_set_src(ui_ui2_Image_bg1, SRC2_PATH_HEAD"red_1.jpg");
    //             lv_img_set_src(ui_ui2_Image_bg2, SRC2_PATH_HEAD"red_2.png");
    //         }
    //     }
    //     else if(t1>=30)
    //     {
    //         if(disp_flag2!=2)
    //         {
    //             disp_flag2=2;
    //             lv_img_cache_invalidate_src(NULL);
    //             lv_img_set_src(ui_ui2_Image_bg1, SRC2_PATH_HEAD"orange_1.jpg");
    //             lv_img_set_src(ui_ui2_Image_bg2, SRC2_PATH_HEAD"orange_2.png");
    //         }
    //     }
    //     else
    //     {
    //         if(disp_flag2!=3)
    //         {
    //             disp_flag2=3;
    //             lv_img_cache_invalidate_src(NULL);
    //             lv_img_set_src(ui_ui2_Image_bg1, SRC2_PATH_HEAD"blue_1.jpg");
    //             lv_img_set_src(ui_ui2_Image_bg2, SRC2_PATH_HEAD"blue_2.png");
    //         }
    //     }

    //     lv_label_set_text(ui_ui2_Label_bgnum, buff);
    //     lv_img_set_angle(ui_ui2_Image_bg1, dongenng_count*10);
    //     lv_img_set_angle(ui_ui2_Image_bg2, 3600-dongenng_count*10);
        //lv_img_set_angle(ui_ui2_Image_bg3, 3600-dongenng_count*10);
        //lv_obj_invalidate(lv_scr_act());//重绘屏幕

    // }

}
///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
#include "app_interface.h"
void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    user_font_init();//初始化字体




    ui_wft_ui1_screen_init();
    lv_disp_load_scr(ui_wft_ui1);

    // ui_wft_ui2_screen_init();
    // lv_disp_load_scr(ui_wft_ui2);

    lv_timer_create(arc_mid_anim, 20, NULL);
    lv_img_cache_set_size(5);



   
}


