// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#define SRC2_PATH_HEAD "L:/rodata/"
#include "ui_helpers.h"
#include "ui_events.h"

#include "app_interface.h"
    // SCREEN: ui_wft_ui1
    extern void ui_wft_ui1_screen_init(void);
    extern lv_obj_t *ui_wft_ui1;
    extern lv_obj_t *ui_Panel1;
    extern lv_obj_t *ui_Panel2;
    extern lv_obj_t *ui_ui1_Image_bg1;
    extern lv_obj_t *ui_ui1_Image_bg2;
    extern lv_obj_t *ui_ui1_Label_bgnum;
    extern lv_obj_t *ui_ui1_Label_kmh;
    extern lv_obj_t *ui_ui1_Slider_bat_left;
    extern lv_obj_t *ui_ui1_Slider_bat_right;
    extern lv_obj_t *ui_Image15;
    extern lv_obj_t *ui_Label3;
    extern lv_obj_t *ui_Image14;
    extern lv_obj_t *ui_Label4;
    extern lv_obj_t *ui_Image18;
    extern lv_obj_t *ui_Image16;
    extern lv_obj_t *ui_Image7;
    extern lv_obj_t *ui_Label5;
    extern lv_obj_t *ui_Label6;
    extern lv_obj_t *ui_Image22;
    extern lv_obj_t *ui_Image21;
    extern lv_obj_t *ui_Image20;
    extern lv_obj_t *ui_Image19;
    extern lv_obj_t *ui_Image17;
    extern lv_obj_t *ui_Image12;
    extern lv_obj_t *ui_Label2;
    extern lv_obj_t *ui_Image13;
    extern lv_obj_t *ui_Image11;
    extern lv_obj_t *ui_Image10;
    extern lv_obj_t *ui_Image5;
    extern lv_obj_t *ui_Image6;
    extern lv_obj_t *ui_Image8;
    extern lv_obj_t *ui_Image9;
    extern lv_obj_t *ui_Image2;
    extern lv_obj_t *ui_Label9;
    extern lv_obj_t *ui_Image4;
    extern lv_obj_t *ui_Image3;
    extern lv_obj_t *ui_Image24;
    extern lv_obj_t *ui_Image25;
    extern lv_obj_t *ui_Image26;
    extern lv_obj_t *ui_Image27;
    extern lv_obj_t *ui_Image28;
    extern lv_obj_t *ui_Image45;
    extern lv_obj_t *ui_Image46;
    extern lv_obj_t *ui_Image47;
    extern lv_obj_t *ui_Image48;
    extern lv_obj_t *ui_Label13;
    // SCREEN: ui_wft_ui2
    extern void ui_wft_ui2_screen_init(void);
    extern lv_obj_t *ui_wft_ui2;
    extern lv_obj_t *ui_ui2_Image_bg1;
    extern lv_obj_t *ui_ui2_Image_bg2;
    extern lv_obj_t *ui_ui2_Label_bgnum;
    extern lv_obj_t *ui_ui2_Label_kmh;
    extern lv_obj_t *ui_Image50;
    extern lv_obj_t *ui_Image29;
    extern lv_obj_t *ui_Image30;
    extern lv_obj_t *ui_Image31;
    extern lv_obj_t *ui_Label14;
    extern lv_obj_t *ui_Label19;
    extern lv_obj_t *ui_Image32;
    extern lv_obj_t *ui_Image33;
    extern lv_obj_t *ui_Image34;
    extern lv_obj_t *ui_Image35;
    extern lv_obj_t *ui_Image36;
    extern lv_obj_t *ui_Image38;
    extern lv_obj_t *ui_Image39;
    extern lv_obj_t *ui_Image37;
    extern lv_obj_t *ui_Label20;
    extern lv_obj_t *ui_Image40;
    extern lv_obj_t *ui_Image41;
    extern lv_obj_t *ui_Image42;
    extern lv_obj_t *ui_Image43;
    extern lv_obj_t *ui_Image44;
    extern lv_obj_t *ui_Label1;
    extern lv_obj_t *ui_Image1;
    extern lv_obj_t *ui_Label8;
    extern lv_obj_t *ui_Label10;
    extern lv_obj_t *ui_Image23;
    extern lv_obj_t *ui_Label11;
    extern lv_obj_t *ui_Image49;
    extern lv_obj_t *ui_Image51;
    extern lv_obj_t *ui_Image52;
    extern lv_obj_t *ui_Image53;
    extern lv_obj_t *ui_Image54;
    extern lv_obj_t *ui_Image55;
    extern lv_obj_t *ui_Image56;
    extern lv_obj_t *ui_Image57;
    extern lv_obj_t *ui_Image58;
    extern lv_obj_t *ui_Image59;
    extern lv_obj_t *ui_Image60;
    extern lv_obj_t *ui_Label12;

    LV_IMG_DECLARE(ui_img_green_1_png);     // assets\green_1.png
    LV_IMG_DECLARE(ui_img_green_2_png);     // assets\green_2.png
    LV_IMG_DECLARE(ui_img_zuo_di2_png);     // assets\zuo_di2.png
    LV_IMG_DECLARE(ui_img_zuo_png);         // assets\zuo.png
    LV_IMG_DECLARE(ui_img_di_you2_png);     // assets\di_you2.png
    LV_IMG_DECLARE(ui_img_you2_png);        // assets\you2.png
    LV_IMG_DECLARE(ui_img_zuo_jiao_png);    // assets\zuo_jiao.png
    LV_IMG_DECLARE(ui_img_you_jiao_png);    // assets\you_jiao.png
    LV_IMG_DECLARE(ui_img_ready_png);       // assets\ready.png
    LV_IMG_DECLARE(ui_img_tubiao1_png);     // assets\tubiao1.png
    LV_IMG_DECLARE(ui_img_p_hui_png);       // assets\P_hui.png
    LV_IMG_DECLARE(ui_img_km_png);          // assets\km.png
    LV_IMG_DECLARE(ui_img_trip_png);        // assets\trip.png
    LV_IMG_DECLARE(ui_img_odo_png);         // assets\odo.png
    LV_IMG_DECLARE(ui_img_tubiao2_png);     // assets\tubiao2.png
    LV_IMG_DECLARE(ui_img_di_inf_png);      // assets\di_inf.png
    LV_IMG_DECLARE(ui_img_inf_png);         // assets\inf.png
    LV_IMG_DECLARE(ui_img_ico_laidian_png); // assets\ico_laidian.png
    LV_IMG_DECLARE(ui_img_ico_l_png);       // assets\ico_l.png
    LV_IMG_DECLARE(ui_img_ico_r_png);       // assets\ico_r.png
    LV_IMG_DECLARE(ui_img_dangwei_png);     // assets\dangwei.png
    LV_IMG_DECLARE(ui_img_r_hui_png);       // assets\R_hui.png
    LV_IMG_DECLARE(ui_img_blue_1_png);      // assets\blue_1.png
    LV_IMG_DECLARE(ui_img_blue_2_png);      // assets\blue_2.png
    LV_IMG_DECLARE(ui_img_daohang_png);     // assets\daohang.png
    LV_IMG_DECLARE(ui_img_diaotou_png);     // assets\diaotou.png
    LV_IMG_DECLARE(ui_img_333_png);         // assets\333.png
    LV_IMG_DECLARE(ui_img_di1_png);         // assets\di1.png
    LV_IMG_DECLARE(ui_img_di2_png);         // assets\di2.png
    LV_IMG_DECLARE(ui_img_di3_png);         // assets\di3.png
    LV_IMG_DECLARE(ui_img_di4_png);         // assets\di4.png
    LV_IMG_DECLARE(ui_img_di_21_png);       // assets\di_21.png
    LV_IMG_DECLARE(ui_img_di_22_png);       // assets\di_22.png
    LV_IMG_DECLARE(ui_img_di_23_png);       // assets\di_23.png
    LV_IMG_DECLARE(ui_img_di_24_png);       // assets\di_24.png
    LV_IMG_DECLARE(ui_img_di_31_png);       // assets\di_31.png
    LV_IMG_DECLARE(ui_img_di_32_png);       // assets\di_32.png
    LV_IMG_DECLARE(ui_img_di_33_png);       // assets\di_33.png
    LV_IMG_DECLARE(ui_img_di_34_png);       // assets\di_34.png
    LV_IMG_DECLARE(ui_img_di_41_png);       // assets\di_41.png
    LV_IMG_DECLARE(ui_img_di_42_png);       // assets\di_42.png
    LV_IMG_DECLARE(ui_img_di_43_png);       // assets\di_43.png
    LV_IMG_DECLARE(ui_img_di_44_png);       // assets\di_44.png
    LV_IMG_DECLARE(ui_img_di_45_png);       // assets\di_45.png
    LV_IMG_DECLARE(ui_img_di_46_png);       // assets\di_46.png
    LV_IMG_DECLARE(ui_img_di_47_png);       // assets\di_47.png
    LV_IMG_DECLARE(ui_img_orange_1_png);    // assets\orange_1.png
    LV_IMG_DECLARE(ui_img_orange_2_png);    // assets\orange_2.png
    LV_IMG_DECLARE(ui_img_red_1_png);       // assets\red_1.png
    LV_IMG_DECLARE(ui_img_red_2_png);       // assets\red_2.png

    LV_IMG_DECLARE(ui_img_youzhuan_png); // assets/youzhuan.png
    LV_IMG_DECLARE(ui_img_zhixing_png);  // assets/zhixing.png
    LV_IMG_DECLARE(ui_img_zuoqian_png);  // assets/zuoqian.png
    LV_IMG_DECLARE(ui_img_zuozhuan_png); // assets/zuozhuan.png

    LV_IMG_DECLARE(ui_img_ico_you_huang_png); // assets/ico_you_huang.png
    LV_IMG_DECLARE(ui_img_ico_jinguang_png);  // assets/ico_jinguang.png
    LV_IMG_DECLARE(ui_img_ico_bt_png);        // assets/ico_bt.png
    LV_IMG_DECLARE(ui_img_ico_m_png);         // assets/ico_m.png
    LV_IMG_DECLARE(ui_img_ico_shache_png);    // assets/ico_shache.png
    LV_IMG_DECLARE(ui_img_ico_zhuanba_png);   // assets/ico_zhuanba.png
    LV_IMG_DECLARE(ui_img_ico_guzhang_png);   // assets/ico_guzhang.png
    LV_IMG_DECLARE(ui_img_ico_ecu_png);       // assets/ico_ecu.png
    LV_IMG_DECLARE(ui_img_ico_dianchi__png);  // assets/ico_dianchi .png
    LV_IMG_DECLARE(ui_img_ico_dadianliu_png); // assets/ico_dadianliu.png
    LV_IMG_DECLARE(ui_img_ico_cecheng_png);   // assets/ico_cecheng.png
    LV_IMG_DECLARE(ui_img_ico_eco_png);       // assets/ico_eco.png

    LV_IMG_DECLARE(ui_img_ico_bt_png);       // assets/ui_img_ico_bt_png.png
    LV_IMG_DECLARE(ui_img_ico_jinguang_png); // assets/ico_jinguang.png
    LV_IMG_DECLARE(ui_img_p_png);            // assets\P.png
    LV_IMG_DECLARE(ui_img_r_png);            // assets\R.png
    LV_IMG_DECLARE(ui_img_d_png);            // assets\D.png
    LV_IMG_DECLARE(ui_img_d_hui_png);        // assets\D_hui.png
    LV_IMG_DECLARE(ui_img_d1_png);           // assets\D1.png
    LV_IMG_DECLARE(ui_img_d1_hui_png);       // assets\D1_hui.png
    LV_IMG_DECLARE(ui_img_d2_png);           // assets\D2.png
    LV_IMG_DECLARE(ui_img_d2_hui_png);       // assets\D2_hui.png
    LV_IMG_DECLARE(ui_img_d3_png);           // assets\D3.png
    LV_IMG_DECLARE(ui_img_d3_hui_png);       // assets\D3_hui.png
    LV_IMG_DECLARE(ui_img_s_hui_png);        // assets\S_hui.png
    LV_IMG_DECLARE(ui_img_s_png);            // assets\S.png

    LV_FONT_DECLARE(ui_font_Font130);

    extern lv_obj_t *ui____initial_actions0;

    // extern lv_style_t type_40_fort;

#define type_40_fort app_interface.font->style
    extern lv_style_t type_130_fort;
    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
