Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
objs = []

if GetDepend("KERNEL_FREERTOS"):
    for d in os.listdir(cwd):
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
