// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_wft_ui2_screen_init(void)
{
    ui_wft_ui2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wft_ui2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_wft_ui2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wft_ui2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_wft_ui2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wft_ui2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ui2_Image_bg1 = lv_img_create(ui_wft_ui2);
    // lv_img_set_src(ui_ui2_Image_bg1, &ui_img_blue_1_png);
    lv_img_set_src(ui_ui2_Image_bg1, SRC2_PATH_HEAD "green_1.png");
    lv_obj_set_width(ui_ui2_Image_bg1, 410);
    lv_obj_set_height(ui_ui2_Image_bg1, 409);
    lv_obj_set_x(ui_ui2_Image_bg1, 15);
    lv_obj_set_y(ui_ui2_Image_bg1, -8);
    lv_obj_set_align(ui_ui2_Image_bg1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ui2_Image_bg1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_ui2_Image_bg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_border_color(ui_ui2_Image_bg1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ui2_Image_bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui2_Image_bg1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui2_Image_bg2 = lv_img_create(ui_ui2_Image_bg1);
    // lv_img_set_src(ui_ui2_Image_bg2, &ui_img_blue_2_png);
    lv_img_set_src(ui_ui2_Image_bg2, SRC2_PATH_HEAD "green_2.png");
    lv_obj_set_width(ui_ui2_Image_bg2, 343);
    lv_obj_set_height(ui_ui2_Image_bg2, 343);
    lv_obj_set_align(ui_ui2_Image_bg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ui2_Image_bg2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_ui2_Image_bg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ui2_Label_bgnum = lv_label_create(ui_ui2_Image_bg1);
    lv_obj_set_width(ui_ui2_Label_bgnum, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ui2_Label_bgnum, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_ui2_Label_bgnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui2_Label_bgnum, "120");

    lv_obj_set_style_text_color(ui_ui2_Label_bgnum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ui2_Label_bgnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ui2_Label_bgnum, &ui_font_Font130, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_add_style(ui_ui2_Label_bgnum,&type_130_fort,0);

    ui_ui2_Label_kmh = lv_label_create(ui_ui2_Image_bg1);
    lv_obj_set_width(ui_ui2_Label_kmh, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ui2_Label_kmh, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ui2_Label_kmh, -5);
    lv_obj_set_y(ui_ui2_Label_kmh, 97);
    lv_obj_set_align(ui_ui2_Label_kmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui2_Label_kmh, "Km/h");
    // lv_obj_set_style_text_color(ui_ui1_Label_bgnum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_ui1_Label_bgnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_ui1_Label_bgnum, &ui_font_Font130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ui2_Label_kmh, &type_40_fort, 0);

    ui_Image50 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image50, &ui_img_daohang_png);
    // lv_img_set_src(ui_Image50, SRC2_PATH_HEAD"daohang.png");
    lv_obj_set_width(ui_Image50, 551);
    lv_obj_set_height(ui_Image50, 600);
    lv_obj_set_align(ui_Image50, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Image50, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image50, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_border_color(ui_Image50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image50, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image29, &ui_img_ready_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);  /// 85
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_Image29, -250);
    lv_obj_set_y(ui_Image29, -270);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image30 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image30, &ui_img_tubiao1_png);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);  /// 40
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT); /// 44
    lv_obj_set_x(ui_Image30, 180);
    lv_obj_set_y(ui_Image30, -270);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image31 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image31, &ui_img_p_hui_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);  /// 34
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT); /// 31
    lv_obj_set_x(ui_Image31, -80);
    lv_obj_set_y(ui_Image31, -270);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label14 = lv_label_create(ui_wft_ui2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label14, -375);
    lv_obj_set_y(ui_Label14, 262);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "0");
    // lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label14, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label14, &type_40_fort, 0);

    ui_Label19 = lv_label_create(ui_wft_ui2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label19, 358);
    lv_obj_set_y(ui_Label19, 271);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "0");
    // lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label19, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label19, &type_40_fort, 0);

    ui_Image32 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image32, &ui_img_km_png);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT); /// 17
    lv_obj_set_x(ui_Image32, 439);
    lv_obj_set_y(ui_Image32, 270);
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image33 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image33, &ui_img_km_png);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT); /// 17
    lv_obj_set_x(ui_Image33, -293);
    lv_obj_set_y(ui_Image33, 261);
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image34 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image34, &ui_img_trip_png);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);  /// 53
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_Image34, 223);
    lv_obj_set_y(ui_Image34, 271);
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image35 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image35, &ui_img_odo_png);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);  /// 56
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT); /// 18
    lv_obj_set_x(ui_Image35, -463);
    lv_obj_set_y(ui_Image35, 263);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image36 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image36, &ui_img_tubiao2_png);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);  /// 59
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT); /// 33
    lv_obj_set_x(ui_Image36, 270);
    lv_obj_set_y(ui_Image36, -270);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image38 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image38, &ui_img_di_inf_png);
    lv_obj_set_width(ui_Image38, LV_SIZE_CONTENT);  /// 403
    lv_obj_set_height(ui_Image38, LV_SIZE_CONTENT); /// 68
    lv_obj_set_x(ui_Image38, -51);
    lv_obj_set_y(ui_Image38, -5);
    lv_obj_set_align(ui_Image38, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image38, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image38, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image39 = lv_img_create(ui_Image38);
    lv_img_set_src(ui_Image39, &ui_img_ico_laidian_png);
    lv_obj_set_width(ui_Image39, 72);
    lv_obj_set_height(ui_Image39, 34);
    lv_obj_set_x(ui_Image39, -149);
    lv_obj_set_y(ui_Image39, 1);
    lv_obj_set_align(ui_Image39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image39, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image39, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image37 = lv_img_create(ui_Image38);
    lv_img_set_src(ui_Image37, &ui_img_inf_png);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);  /// 38
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT); /// 35
    lv_obj_set_x(ui_Image37, -148);
    lv_obj_set_y(ui_Image37, 0);
    lv_obj_set_align(ui_Image37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image37, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label20 = lv_label_create(ui_Image38);
    lv_obj_set_width(ui_Label20, 250);
    lv_obj_set_height(ui_Label20, 46);
    lv_obj_set_x(ui_Label20, 16);
    lv_obj_set_y(ui_Label20, 1);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "13888888888");
    lv_label_set_recolor(ui_Label20, "true");
    // lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label20, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_Label20, 275);
    lv_label_set_long_mode(ui_Label20, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_style_anim_speed(ui_Label20, 100, 0);

    lv_obj_add_style(ui_Label20, &type_40_fort, 0);

    ui_Image40 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image40, &ui_img_d1_png);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);  /// 55
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT); /// 32
    lv_obj_set_x(ui_Image40, 83);
    lv_obj_set_y(ui_Image40, -270);
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image41 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image41, &ui_img_ico_l_png);
    lv_obj_set_width(ui_Image41, LV_SIZE_CONTENT);  /// 72
    lv_obj_set_height(ui_Image41, LV_SIZE_CONTENT); /// 53
    lv_obj_set_x(ui_Image41, -468);
    lv_obj_set_y(ui_Image41, -269);
    lv_obj_set_align(ui_Image41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image41, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image41, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image42 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image42, &ui_img_ico_r_png);
    lv_obj_set_width(ui_Image42, LV_SIZE_CONTENT);  /// 72
    lv_obj_set_height(ui_Image42, LV_SIZE_CONTENT); /// 53
    lv_obj_set_x(ui_Image42, 467);
    lv_obj_set_y(ui_Image42, -269);
    lv_obj_set_align(ui_Image42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image42, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image42, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image43 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image43, &ui_img_dangwei_png);
    lv_obj_set_width(ui_Image43, LV_SIZE_CONTENT);  /// 96
    lv_obj_set_height(ui_Image43, LV_SIZE_CONTENT); /// 61
    lv_obj_set_x(ui_Image43, 80);
    lv_obj_set_y(ui_Image43, -270);
    lv_obj_set_align(ui_Image43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image43, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image43, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image44 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image44, &ui_img_r_hui_png);
    lv_obj_set_width(ui_Image44, LV_SIZE_CONTENT);  /// 37
    lv_obj_set_height(ui_Image44, LV_SIZE_CONTENT); /// 31
    lv_obj_set_x(ui_Image44, 0);
    lv_obj_set_y(ui_Image44, -270);
    lv_obj_set_align(ui_Image44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image44, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image44, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label1 = lv_label_create(ui_wft_ui2);
    lv_obj_set_width(ui_Label1, 359);
    lv_obj_set_height(ui_Label1, 163);
    lv_obj_set_x(ui_Label1, 308);
    lv_obj_set_y(ui_Label1, -53);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "100米后掉头，进入广深公路，当前限速80Km/h");
    lv_obj_clear_flag(ui_Label1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                                     LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_Label1, LV_SCROLLBAR_MODE_OFF);
    // lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_letter_space(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_line_space(ui_Label1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label1, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label1, &type_40_fort, 0);

    ui_Image1 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image1, &ui_img_diaotou_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 106
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 118
    lv_obj_set_x(ui_Image1, 67);
    lv_obj_set_y(ui_Image1, -55);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label8 = lv_label_create(ui_wft_ui2);
    lv_obj_set_width(ui_Label8, 433);
    lv_obj_set_height(ui_Label8, 58);
    lv_obj_set_x(ui_Label8, 290);
    lv_obj_set_y(ui_Label8, 116);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "剩余 5 Km   15 分钟");
    // lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label8, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label8, &type_40_fort, 0);

    ui_Label10 = lv_label_create(ui_wft_ui2);
    lv_obj_set_width(ui_Label10, 426);
    lv_obj_set_height(ui_Label10, 57);
    lv_obj_set_x(ui_Label10, 284);
    lv_obj_set_y(ui_Label10, 184);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "预计 18:34 到达");
    // lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label10, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label10, &type_40_fort, 0);

    ui_Image23 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image23, &ui_img_ico_jinguang_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);  /// 85
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_Image23, -156);
    lv_obj_set_y(ui_Image23, -270);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label11 = lv_label_create(ui_wft_ui2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label11, 100);
    lv_obj_set_y(ui_Label11, -212);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "12:45");
    // lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label11, &ui_font_Fontch42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label11, &type_40_fort, 0);

    //  天气   start
    ui_Label12 = lv_label_create(ui_wft_ui2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT); /// 1
    lv_obj_set_width(ui_Label12, 320);
    lv_obj_set_height(ui_Label12, 100);
    lv_obj_set_x(ui_Label12, 340);
    lv_obj_set_y(ui_Label12, -180);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "四川成都 暴雨 9℃ ~ 20℃ ");
    // lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label11, &ui_font_Fontch42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label12, &app_font.style_font_16, 0);
    //  天气   end

    ui_Image49 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image49, &ui_img_ico_bt_png);
    lv_obj_set_width(ui_Image49, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image49, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image49, -351);
    lv_obj_set_y(ui_Image49, -270);
    lv_obj_set_align(ui_Image49, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image49, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image49, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image51 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image51, &ui_img_ico_zhuanba_png);
    lv_obj_set_width(ui_Image51, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image51, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image51, -115);
    lv_obj_set_y(ui_Image51, -220);
    lv_obj_set_align(ui_Image51, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image51, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image51, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image52 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image52, &ui_img_ico_cecheng_png);
    lv_obj_set_width(ui_Image52, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image52, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image52, -59);
    lv_obj_set_y(ui_Image52, -220);
    lv_obj_set_align(ui_Image52, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image52, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image52, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image53 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image53, &ui_img_ico_dadianliu_png);
    lv_obj_set_width(ui_Image53, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image53, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image53, -10);
    lv_obj_set_y(ui_Image53, -220);
    lv_obj_set_align(ui_Image53, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image53, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image53, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image54 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image54, &ui_img_ico_dianchi__png);
    lv_obj_set_width(ui_Image54, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image54, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image54, -135);
    lv_obj_set_y(ui_Image54, -170);
    lv_obj_set_align(ui_Image54, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image54, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image54, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image55 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image55, &ui_img_ico_ecu_png);
    lv_obj_set_width(ui_Image55, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image55, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image55, -77);
    lv_obj_set_y(ui_Image55, -119);
    lv_obj_set_align(ui_Image55, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image55, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image55, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image56 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image56, &ui_img_ico_guzhang_png);
    lv_obj_set_width(ui_Image56, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image56, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image56, -171);
    lv_obj_set_y(ui_Image56, -220);
    lv_obj_set_align(ui_Image56, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image56, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image56, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image57 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image57, &ui_img_ico_m_png);
    lv_obj_set_width(ui_Image57, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image57, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image57, -30);
    lv_obj_set_y(ui_Image57, -170);
    lv_obj_set_align(ui_Image57, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image57, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image57, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image58 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image58, &ui_img_ico_shache_png);
    lv_obj_set_width(ui_Image58, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image58, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image58, -81);
    lv_obj_set_y(ui_Image58, -170);
    lv_obj_set_align(ui_Image58, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image58, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image58, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image59 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image59, &ui_img_ico_you_huang_png);
    lv_obj_set_width(ui_Image59, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image59, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image59, -460);
    lv_obj_set_y(ui_Image59, 187);
    lv_obj_set_align(ui_Image59, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image59, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image59, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image60 = lv_img_create(ui_wft_ui2);
    lv_img_set_src(ui_Image60, &ui_img_ico_eco_png);
    lv_obj_set_width(ui_Image60, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image60, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image60, -454);
    lv_obj_set_y(ui_Image60, -206);
    lv_obj_set_align(ui_Image60, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image60, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image60, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_add_flag(ui_Label20, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Label19, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Label14, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Label11, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image56, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image59, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image52, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image53, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image54, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image58, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image51, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image55, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image57, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image60, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image49, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image41, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image42, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image39, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_ui2_Label_bgnum, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_ui2_Label_kmh, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_flag(ui_Label12, LV_OBJ_FLAG_HIDDEN); /// 天气
}
