// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_wft_ui1_screen_init(void)
{
    ui_wft_ui1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wft_ui1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_wft_ui1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wft_ui1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_wft_ui1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wft_ui1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_wft_ui1);
    lv_obj_set_width(ui_Panel1, 1);
    lv_obj_set_height(ui_Panel1, 200);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_wft_ui1);
    lv_obj_set_width(ui_Panel2, 1);
    lv_obj_set_height(ui_Panel2, 200);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel2, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui1_Image_bg1 = lv_img_create(ui_wft_ui1);
    // lv_img_set_src(ui_ui1_Image_bg1, &ui_img_green_1_png);
    lv_img_set_src(ui_ui1_Image_bg1, SRC2_PATH_HEAD "green_1.png");
    lv_obj_set_width(ui_ui1_Image_bg1, 410);
    lv_obj_set_height(ui_ui1_Image_bg1, 409);
    lv_obj_set_x(ui_ui1_Image_bg1, 0);
    lv_obj_set_y(ui_ui1_Image_bg1, -33);
    lv_obj_set_align(ui_ui1_Image_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ui1_Image_bg1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_ui1_Image_bg1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_border_color(ui_ui1_Image_bg1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ui1_Image_bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui1_Image_bg1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui1_Image_bg2 = lv_img_create(ui_ui1_Image_bg1);
    // lv_img_set_src(ui_ui1_Image_bg2, &ui_img_green_2_png);
    lv_img_set_src(ui_ui1_Image_bg2, SRC2_PATH_HEAD "green_2.png");
    lv_obj_set_width(ui_ui1_Image_bg2, 343);
    lv_obj_set_height(ui_ui1_Image_bg2, 343);
    lv_obj_set_align(ui_ui1_Image_bg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ui1_Image_bg2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_ui1_Image_bg2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ui1_Label_bgnum = lv_label_create(ui_ui1_Image_bg1);
    lv_obj_set_width(ui_ui1_Label_bgnum, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ui1_Label_bgnum, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ui1_Label_bgnum, -4);
    lv_obj_set_y(ui_ui1_Label_bgnum, -10);
    lv_obj_set_align(ui_ui1_Label_bgnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui1_Label_bgnum, "0");
    lv_obj_set_style_text_color(ui_ui1_Label_bgnum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ui1_Label_bgnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ui1_Label_bgnum, &ui_font_Font130, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_add_style(ui_ui1_Label_bgnum, &type_130_fort, 0);

    ui_ui1_Label_kmh = lv_label_create(ui_ui1_Image_bg1);
    lv_obj_set_width(ui_ui1_Label_kmh, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ui1_Label_kmh, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ui1_Label_kmh, -3);
    lv_obj_set_y(ui_ui1_Label_kmh, 83);
    lv_obj_set_align(ui_ui1_Label_kmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui1_Label_kmh, "Km/h");
    // lv_obj_set_style_text_color(ui_ui1_Label_kmh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_ui1_Label_kmh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_ui1_Label_kmh, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_ui1_Label_kmh, &type_40_fort, 0);
#if 1
    ui_ui1_Slider_bat_left = lv_slider_create(ui_wft_ui1);
    lv_slider_set_value(ui_ui1_Slider_bat_left, 100, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_ui1_Slider_bat_left) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_ui1_Slider_bat_left,
                                 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ui1_Slider_bat_left, 162);
    lv_obj_set_height(ui_ui1_Slider_bat_left, 378);
    lv_obj_set_x(ui_ui1_Slider_bat_left, -348);
    lv_obj_set_y(ui_ui1_Slider_bat_left, -33);
    lv_obj_set_align(ui_ui1_Slider_bat_left, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ui1_Slider_bat_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui1_Slider_bat_left, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui1_Slider_bat_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ui1_Slider_bat_left, &ui_img_zuo_di2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ui1_Slider_bat_left, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ui1_Slider_bat_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui1_Slider_bat_left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ui1_Slider_bat_left, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui1_Slider_bat_left, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui1_Slider_bat_left, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ui1_Slider_bat_left, &ui_img_zuo_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ui1_Slider_bat_left, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui1_Slider_bat_left, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui1_Slider_bat_left, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ui1_Slider_bat_right = lv_slider_create(ui_wft_ui1);
    lv_slider_set_value(ui_ui1_Slider_bat_right, 100, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_ui1_Slider_bat_right) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_ui1_Slider_bat_right, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ui1_Slider_bat_right, 162);
    lv_obj_set_height(ui_ui1_Slider_bat_right, 378);
    lv_obj_set_x(ui_ui1_Slider_bat_right, 355);
    lv_obj_set_y(ui_ui1_Slider_bat_right, -33);
    lv_obj_set_align(ui_ui1_Slider_bat_right, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ui1_Slider_bat_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui1_Slider_bat_right, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui1_Slider_bat_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ui1_Slider_bat_right, &ui_img_di_you2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ui1_Slider_bat_right, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ui1_Slider_bat_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui1_Slider_bat_right, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ui1_Slider_bat_right, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui1_Slider_bat_right, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui1_Slider_bat_right, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ui1_Slider_bat_right, &ui_img_you2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ui1_Slider_bat_right, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui1_Slider_bat_right, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui1_Slider_bat_right, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
#endif
    ui_Image15 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image15, &ui_img_zuo_jiao_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);  /// 125
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT); /// 138
    lv_obj_set_x(ui_Image15, -430);
    lv_obj_set_y(ui_Image15, -33);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label3 = lv_label_create(ui_Image15);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 3);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "0%");
    // lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label3, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label3, &type_40_fort, 0);

    ui_Image14 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image14, &ui_img_you_jiao_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);  /// 125
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT); /// 138
    lv_obj_set_x(ui_Image14, 421);
    lv_obj_set_y(ui_Image14, -33);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label4 = lv_label_create(ui_Image14);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label4, 10);
    lv_obj_set_y(ui_Label4, 3);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "0.0V");
    // lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label4, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label4, &type_40_fort, 0);

    ui_Image18 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image18, &ui_img_ready_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);  /// 85
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT); /// 20
    lv_obj_set_x(ui_Image18, -250);
    lv_obj_set_y(ui_Image18, -270);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image16 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image16, &ui_img_tubiao1_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);  /// 40
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT); /// 44
    lv_obj_set_x(ui_Image16, 180);
    lv_obj_set_y(ui_Image16, -270);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label5 = lv_label_create(ui_wft_ui1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label5, -374);
    lv_obj_set_y(ui_Label5, 262);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "0");
    // lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label5, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label5, &type_40_fort, 0);

    ui_Label6 = lv_label_create(ui_wft_ui1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label6, 388);
    lv_obj_set_y(ui_Label6, 260);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "0");
    // lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label6, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label6, &type_40_fort, 0);

    ui_Image22 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image22, &ui_img_km_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT); /// 17
    lv_obj_set_x(ui_Image22, 462);
    lv_obj_set_y(ui_Image22, 260);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image21 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image21, &ui_img_km_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT); /// 17
    lv_obj_set_x(ui_Image21, -296);
    lv_obj_set_y(ui_Image21, 263);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image20 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image20, &ui_img_trip_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);  /// 53
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_Image20, 299);
    lv_obj_set_y(ui_Image20, 260);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image19 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image19, &ui_img_odo_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);  /// 56
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT); /// 18
    lv_obj_set_x(ui_Image19, -460);
    lv_obj_set_y(ui_Image19, 260);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image17 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image17, &ui_img_tubiao2_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);  /// 59
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT); /// 33
    lv_obj_set_x(ui_Image17, 270);
    lv_obj_set_y(ui_Image17, -270);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image12 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image12, &ui_img_di_inf_png);
    lv_obj_set_width(ui_Image12, 403);
    lv_obj_set_height(ui_Image12, 68);
    lv_obj_set_x(ui_Image12, 6);
    lv_obj_set_y(ui_Image12, -9);
    lv_obj_set_align(ui_Image12, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_border_color(ui_Image12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Image12);
    lv_obj_set_x(ui_Label2, 14);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "13888888888");
    lv_label_set_recolor(ui_Label2, "true");

    lv_obj_set_width(ui_Label2, 275);
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_style_anim_speed(ui_Label2, 100, 0);
    // lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label2, &ui_font_Fontch55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label2, &type_40_fort, 0);

    ui_Image13 = lv_img_create(ui_Image12);
    lv_img_set_src(ui_Image13, &ui_img_inf_png);
    lv_obj_set_x(ui_Image13, -161);
    lv_obj_set_y(ui_Image13, 2);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image11 = lv_img_create(ui_Image12);
    lv_img_set_src(ui_Image11, &ui_img_ico_laidian_png);
    lv_obj_set_width(ui_Image11, 72);
    lv_obj_set_height(ui_Image11, 34);
    lv_obj_set_x(ui_Image11, -162);
    lv_obj_set_y(ui_Image11, 3);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image5 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image5, &ui_img_ico_l_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);  /// 72
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT); /// 53
    lv_obj_set_x(ui_Image5, -468);
    lv_obj_set_y(ui_Image5, -269);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image6 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image6, &ui_img_ico_r_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);  /// 72
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT); /// 53
    lv_obj_set_x(ui_Image6, 467);
    lv_obj_set_y(ui_Image6, -269);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // D 档
    ui_Image8 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image8, &ui_img_dangwei_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);  /// 96
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT); /// 61
    lv_obj_set_x(ui_Image8, 80);
    lv_obj_set_y(ui_Image8, -270);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image10 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image10, &ui_img_d1_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);  /// 55
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT); /// 32
    lv_obj_set_x(ui_Image10, 83);
    lv_obj_set_y(ui_Image10, -270);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image7 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image7, &ui_img_p_hui_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);  /// 34
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT); /// 31
    lv_obj_set_x(ui_Image7, -80);
    lv_obj_set_y(ui_Image7, -270);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image9 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image9, &ui_img_r_hui_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);  /// 37
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT); /// 31
    lv_obj_set_x(ui_Image9, 0);
    lv_obj_set_y(ui_Image9, -270);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image2 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image2, &ui_img_ico_jinguang_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image2, -156);
    lv_obj_set_y(ui_Image2, -270);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label9 = lv_label_create(ui_wft_ui1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label9, 390);
    lv_obj_set_y(ui_Label9, 207);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "12:30");
    // lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label9, &ui_font_Fontch42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label9, &type_40_fort, 0);

    //  天气   start
    ui_Label13 = lv_label_create(ui_wft_ui1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT); /// 1
    lv_obj_set_width(ui_Label13, 400);
    lv_obj_set_height(ui_Label13, 20);
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 207);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "四川成都 暴雨 9℃ ~ 20℃ ");
    // lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_Label13, &ui_font_Fontch42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_style(ui_Label13, &app_font.style_font_16, 0);
    //  天气   end

    ui_Image4 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image4, &ui_img_ico_bt_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image4, -351);
    lv_obj_set_y(ui_Image4, -270);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image3 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image3, &ui_img_ico_m_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image3, -476);
    lv_obj_set_y(ui_Image3, -204);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image24 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image24, &ui_img_ico_shache_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image24, -411);
    lv_obj_set_y(ui_Image24, -204);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image25 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image25, &ui_img_ico_zhuanba_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image25, -474);
    lv_obj_set_y(ui_Image25, -154);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image26 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image26, &ui_img_ico_guzhang_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image26, 429);
    lv_obj_set_y(ui_Image26, -204);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image27 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image27, &ui_img_ico_ecu_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image27, 480);
    lv_obj_set_y(ui_Image27, -204);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image28 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image28, &ui_img_ico_dianchi__png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image28, 480);
    lv_obj_set_y(ui_Image28, -154);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image45 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image45, &ui_img_ico_dadianliu_png);
    lv_obj_set_width(ui_Image45, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image45, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image45, -474);
    lv_obj_set_y(ui_Image45, 122);
    lv_obj_set_align(ui_Image45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image45, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image45, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image46 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image46, &ui_img_ico_cecheng_png);
    lv_obj_set_width(ui_Image46, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image46, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image46, -422);
    lv_obj_set_y(ui_Image46, 122);
    lv_obj_set_align(ui_Image46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image46, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image46, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image47 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image47, &ui_img_ico_eco_png);
    lv_obj_set_width(ui_Image47, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image47, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image47, 469);
    lv_obj_set_y(ui_Image47, 133);
    lv_obj_set_align(ui_Image47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image47, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image47, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image48 = lv_img_create(ui_wft_ui1);
    lv_img_set_src(ui_Image48, &ui_img_ico_you_huang_png);
    lv_obj_set_width(ui_Image48, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image48, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image48, -466);
    lv_obj_set_y(ui_Image48, 192);
    lv_obj_set_align(ui_Image48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image48, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image48, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    //  默认不显示这些图标

    // ui_wft_ui1;
    // ui_ui1_Image_bg1;
    // ui_ui1_Image_bg2;
    // ui_ui1_Label_bgnum;
    // ui_ui1_Label_kmh;
    // ui_ui1_Slider_bat_left;
    // ui_ui1_Slider_bat_right;
    // ui_Image15;
    // ui_Label3;
    // ui_Image14;
    // ui_Label4;
    // ui_Image18;
    // ui_Image16;
    // ui_Image7;
    // ui_Label5;
    // ui_Label6;
    // ui_Image22;
    // ui_Image21;
    // ui_Image20;
    // ui_Image19;
    // ui_Image17;
    // ui_Image12;
    // ui_Label2;
    // ui_Image13;
    // ui_Image11;
    // ui_Image10;
    // ui_Image5;
    // ui_Image6;
    // ui_Image8;
    // ui_Image9;
    // ui_Image2;
    // ui_Label9;
    // ui_Image4;
    // ui_Image3;
    // ui_Image24;
    // ui_Image25;
    // ui_Image26;
    // ui_Image27;
    // ui_Image28;
    // ui_Image45;
    // ui_Image46;
    // ui_Image47;
    // ui_Image48;
    
    
    // lv_obj_add_flag(ui_Label4, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Label6, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Label5, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Label9, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Label2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Label3, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_ui1_Label_kmh, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_ui1_Label_bgnum, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Label3, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image45, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image46, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image47, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image48, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_HIDDEN);  /// Flags 转向左
    // lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_HIDDEN); /// Flags 转向左
    // lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_HIDDEN);  /// Flags 转向右
    // lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_HIDDEN); /// Flags call
    // lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_HIDDEN); // 定速巡航
    // lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_HIDDEN); /// Flags  短信

    // lv_obj_add_flag(ui_Label13, LV_OBJ_FLAG_HIDDEN); /// 天气
}
